env:
  global:
  - CONAN_USERNAME: rhololkeolke
  - CONAN_LOGIN_USERNAME: rhololkeolke
  - CONAN_CHANNEL: stable
  - CONAN_UPLOAD: https://api.bintray.com/conan/rhololkeolke/public-conan
  - CONAN_STABLE_BRANCH_PATTERN: stable/*
  - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  - CONAN_ARCHS: x86_64
  - CONAN_BUILD_POLICY: outdated
  - secure: I948l2b7fgeXLF5meX2mVoGl+BBudmcPJwnSgqjpoXfJocmUUekNkvQGUDta5oYtT7/bilM7p2U/57bK6ikR/V1KZA9BSBFiVLb55MFv/8IBlNVDGBmQYLP3uOd5OktagSfDVfdbIYxjgk2yV8GLmwY6NJQi3QICj+sFg80ufD4YlP6I59o6N1N0Mw6hunJd9TzsadNZnEvqsPRU4lIG+Hs4uALbfK7ZLTFFgpxJpqX9pTFG/EyOoWR00aWQezoyPDqPxMZkF3TWoMS+2pUOr4H1hMAeWzIggCFvb6s+Of4mBFHIno60IB+GfjtbIbcie7ZEsmKvAVTQmuuujEAXA6/Ohew1L/3nbzdvxx19fK8MMpbb4061w/UFz/0rZk4QK1rt14JDzCGBBO2jIjz3PpabivGhs06YMqlWUzibyko9NFJS/lc05YkQjzEnb1vby2SuQntKsbipfZJQPAn+ox6muXxeyibvivinVDmFq88zPxx8FHKwRgR5mCF2UctH/D4utUFGuSGa2wFSBlrdZCC65sHdYv23oEh+LAXcHh2fHtQaGrWyswmNeIRhG9y2eOql/VsqwRuAWhviCklhfdt5oCKmwMaFlXRN4iXgzJbDefpTieykCEIG8o77UHt8MsjgWapAveoffTSPikDtAbgJ7FwnIDDiDZ1Mc8C+TFU=
linux: &linux
  os: linux
  dist: xenial
  sudo: required
  language: python
  python: '3.7'
  services: 
    - docker
matrix:
  include:
  - <<: *linux
    env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
  - <<: *linux
    env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8
install:
  - chmod +x .travis/install.sh
  - "./.travis/install.sh"
script:
  - chmod +x .travis/run.sh
  - "./.travis/run.sh"
